### ISSUE TITLE
Add node.js configuration

### ISSUE THREAD

**Issue by oxrc** [oxrc/itstep_jscript_1614#26]
A simple node.js configuration file using package.json should be added. As mandatory package we should have [expressjs](http://expressjs.com/) . More about how to do it [here](http://expressjs.com/en/starter/installing.html).

**Comment by xpycmuk** [comment]
In  [documentation](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) is sad
> The "author" is one person. "contributors" is an array of people

since we are developing this project in group, i suggest:

put "contributors" instead of "author" and mention all our names
or
leave "author" and mention our group name

P.S.
refer to pull request #38

**Comment by oxrc** [comment]
@xpycmuk this is already merged. If the naming will bother us in the future - we'll make a new task and change them. Closing this task.
